### ISSUE TITLE
Citizen object set in the "setCitizen" method of the chaincode is not correct

### ISSUE THREAD

**Issue by agamvrinos** [hyperdebt/blockchain#10]
Based on the user interface, the correct structure is:

- bsn
- firstName
- lastName
- address 
- salary **(This is going to be changed to "financialSupport")** #1
- consent
- JSON object indicating the municipality id.

The fields that are now stored are:

- bsn
- name
- addressCity
- addressStreet

**Comment by Yzoni** [comment]
Just like in #5, I think bsn needs to be removed.

**Comment by agamvrinos** [comment]
Ye this is before applying private data. With this in mind, bsn should not be included.
