### ISSUE TITLE
Change POST request to GET when requesting citizen info

### ISSUE THREAD

**Issue by agamvrinos** [hyperdebt/blockchain#17]

**Comment by Yzoni** [comment]
I dont agree with this, all of the data we will send is sensitive even when we remove the BSN. I dont think this should be sent using GET.

**Comment by agamvrinos** [comment]
Hmm what you say makes sense. I was thinking that since we're re querying information (and not creating or updating) GET is more correct based on the REST standards. However, I dont think that POST provides that much of privacy (other than sending the parameters in the body instead of the URL)

https://stackoverflow.com/questions/198462/is-either-get-or-post-more-secure-than-the-other

**Comment by Yzoni** [comment]
You are right both ways the data is encrypted using tls, but In a real life situation you might have some access log in which the requested urls containing with the private data are saved. If it is easier for the ui then just leave it like this.
