### ISSUE TITLE
Build the REST API using the NodeJS sdk

### ISSUE THREAD

**Issue by agamvrinos** [hyperdebt/blockchain#4]
Build the rest server. The client apps will request/update information on the blockchain by using the respective methods exposed by the rest server.

**REST Server How-To:** https://hackernoon.com/setting-up-restful-api-server-for-hyperledger-fabric-with-nodejs-sdk-a4642edaf98e

**Comment by agamvrinos** [comment]
This also might be useful for the REST api implementation: https://medium.com/wearetheledger/hyperledger-fabric-typescript-boilerplate-455004d0c6c8

**Comment by Yzoni** [comment]
Maybe not the prettiest, but it works: https://github.com/hyperdebt/blockchain/commit/73da37df22335298eff1f12e02ae4db1f62292bd
