### ISSUE TITLE
Add ability to query individual blocks

### ISSUE THREAD

**Issue by Yzoni** [hyperdebt/blockchain#7]
https://hyperledger-fabric.readthedocs.io/en/release-1.3/peer-commands.html#id4

https://fabric-sdk-node.github.io/BlockDecoder.html#.decodeTransaction__anchor

**Comment by NomelemoN** [comment]
I added 3 commands to the dev makefile: query-latest-block, query-newest-block and query-specific-block. The latter takes a blocknumber as input. The blocks are stored in fabric-network-dev/bin/blocks.
