### ISSUE TITLE
Setup network consisting of at least 5 peer nodes

### ISSUE THREAD

**Issue by Yzoni** [hyperdebt/blockchain#8]
To simulate the peers of multiple municipalities.

**Comment by NomelemoN** [comment]
I have created a new makefile for the realnetwork (realnet.mk), of which the commands can be used via make -f realnet.mk *command*. Using this makefile, 5 peer nodes are created, a channel is created, and they all join the channel. Installing and instantiating the chaincode seems like it works (based on command line) but I still need to test that with an actual query. There is still only one orderer node (which is okay for development environment but not for production). I'll probably work next on adding 5 orderer nodes that use kafka.
